//========================================================================
// Adder_8b (generated by schematic2verilog)
//========================================================================

`ifndef ADDER_8B_V
`define ADDER_8B_V

`include "ref/FullAdder.v"

module Adder_8b
(
  input  logic in0[7:0],
  input  logic in1[7:0],
  output logic sum[7:0]
);

  supply0 gnd;

  logic [6:0] C;
  logic [7:0] in0;
  logic [7:0] in1;
  logic [7:0] sum;

  FullAdder I3
  (
    .S    (sum[7]),
    .B    (in1[7]),
    .A    (in0[7]),
    .Cin  (C[6]),
    .Cout ()
  );

  FullAdder I1_6
  (
    .S    (sum[6]),
    .B    (in1[6]),
    .A    (in0[6]),
    .Cin  (C[5]),
    .Cout (C[6])
  );

  FullAdder I1_5
  (
    .S    (sum[5]),
    .B    (in1[5]),
    .A    (in0[5]),
    .Cin  (C[4]),
    .Cout (C[5])
  );

  FullAdder I1_4
  (
    .S    (sum[4]),
    .B    (in1[4]),
    .A    (in0[4]),
    .Cin  (C[3]),
    .Cout (C[4])
  );

  FullAdder I1_3
  (
    .S    (sum[3]),
    .B    (in1[3]),
    .A    (in0[3]),
    .Cin  (C[2]),
    .Cout (C[3])
  );

  FullAdder I1_2
  (
    .S    (sum[2]),
    .B    (in1[2]),
    .A    (in0[2]),
    .Cin  (C[1]),
    .Cout (C[2])
  );

  FullAdder I1_1
  (
    .S    (sum[1]),
    .B    (in1[1]),
    .A    (in0[1]),
    .Cin  (C[0]),
    .Cout (C[1])
  );

  FullAdder I0
  (
    .S    (sum[0]),
    .B    (in1[0]),
    .A    (in0[0]),
    .Cin  (gnd),
    .Cout (C[0])
  );

endmodule

`endif /* ADDER_8B_V */
